dist: xenial
cache:
  directories:
  - "~/.go"
install:
  - sudo ./build-bsdtar.sh
script:
  - sudo ./build-arch-arm-img.sh http://os.archlinuxarm.org/os/ArchLinuxARM-rpi-3-latest.tar.gz
  - sudo ./build-arch-arm-img.sh http://os.archlinuxarm.org/os/ArchLinuxARM-rpi-2-latest.tar.gz
deploy:
  provider: releases
  api_key:
    secure: Hy0s03T0K0ZbgmzzB0Cepz2zUczGF6ryechV6UqGk+kNsn+bUOjROQkugLVwqZhm54ePUeYJ5CejKJgkQKRJCFZHzs3CZmQZPW5eRbaWP8N2qv6ktaW9XQpRs4jkkcG5o4Wuz4P79rCMbXDQEJ44R3o/Ov05nyRLpLb69MetCokeJzWZwFYhnHV6mDyMoYVzzOdWavlyjvmJ0jQgln3T68MxqRIO0yBjeHqQAluu2NsrZovzsCOm6DxuhzzFYojfdpo8OwOqkzRztzRxPUqxczbbtyefwyx1SfqMOmPC8XLIokgCg356UygQs+RiQNmTfCae/+FUOm+mQm1XEtvJUThJlWyd7I1+l1gi/hbThqjcTfhx4YBiybSUGeeOeYsdLbNfzBYo8c4tsAHV1LqPZyy0F5PnSRdS1Y0kxObHQ45gYz4RKhVo9MGva0UWRBqrx916czG45MpU0pqpUz1wu61n2XeAdj/4bkY1J3zq/CP/EeOWaHphXHfWed5PfPTppruKfILw+ytBGH/GLbnD22q5n46yWvHKF2CVUtd150AY9p2CAOWdItHmbXMziTcpMtqr2R4MMjVAr3Rf4JcNe4OtKIn9FEwZDiEw76QuOkO2rgL8mGuPI7acCRtZZcxK6kt0fMNpdt5bIzMdz1AWvxus+1PdYpbRg02Jx5Gmj7U=
  file_glob: true
  file: ArchLinuxARM-*.{img,md5}
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    repo: bcomnes/archlinux-arm-img
