dist: xenial
cache:
  directories:
  - "./images"
  - "./libarchive-3.3.1"
install:
- sudo ./build-bsdtar.sh
script:
- sudo ./build-arch-arm-img.sh http://os.archlinuxarm.org/os/ArchLinuxARM-rpi-3-latest.tar.gz
- sudo ./build-arch-arm-img.sh http://os.archlinuxarm.org/os/ArchLinuxARM-rpi-2-latest.tar.gz
deploy:
  provider: releases
  api_key: $GITHUB_PAT
  file_glob: true
  file: ArchLinuxARM-*.{img,md5}
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    repo: bcomnes/archlinux-arm-img
