dist: xenial
cache:
  directories:
  - "./images"
  - "./libarchive-3.3.1"
install:
- sudo ./build-bsdtar.sh
script:
- sudo ./build-arch-arm-img.sh http://os.archlinuxarm.org/os/ArchLinuxARM-rpi-3-latest.tar.gz
- sudo ./build-arch-arm-img.sh http://os.archlinuxarm.org/os/ArchLinuxARM-rpi-2-latest.tar.gz
stages:
  - name: before_deploy
    if: $TRAVIS_EVENT_TYPE = cron
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "Bret Comnes"
  - git config --local user.email "bcomnes@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: $GITHUB_PAT
  file_glob: true
  file: ArchLinuxARM-*.{img,md5}
  skip_cleanup: true
  overwrite: true
  on:
    repo: bcomnes/archlinux-arm-img
    tag: true
