
name: build

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        release:
        - ArchLinuxARM-rpi-3-latest
        - ArchLinuxARM-rpi-2-latest
        - ArchLinuxARM-rpi-4-latest

    env:
      TARGET_IMG: ${{ matrix.release }}
      LIBARCHIVE_VERSION: 3.4.2

    steps:
    - uses: actions/checkout@v2

    - name: Cache libarchive build
      uses: actions/cache@v1
      with:
        path: ./libarchive-${{env.LIBARCHIVE_VERSION}}
        key: libarchive-${{env.LIBARCHIVE_VERSION}}

    - name: Cache images
      uses: actions/cache@v1
      with:
        path: ./images
        key: images-${{env.TARGET_IMG}}

    - name: install libarchive
      run: |
        sudo ./build-bsdtar.sh $LIBARCHIVE_VERSION
    - name: build iso
      run: |
        sudo ./build-arch-arm-img.sh $TARGET_IMG

    - name: Upload img
      uses: actions/upload-artifact@v1
      with:
        path: ${{env.TARGET_IMG}}.zip
    - name: Upload md5
      uses: actions/upload-artifact@v1
      with:
        path: ${{env.TARGET_IMG}}.md5
